type: "transformation"
version: "1.0"
pipeline:
  components:
    bronze_data:
      type: "table-input"
      parameters:
        componentName: "bronze_data"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "bronze_data"
        columnNames:
        - "ID"
        - "VALUE"
        timeOffset:
    Stats:
      type: "aggregate"
      sources:
      - "bronze_data"
      parameters:
        componentName: "Stats"
        groupings:
        aggregations:
        - - "VALUE"
          - "Average"
        - - "VALUE"
          - "Standard Deviation - Population"
        groupingType: "Group By"
    Join:
      type: "join"
      sources:
      - "bronze_data"
      - "Stats"
      parameters:
        componentName: "Join"
        mainTable: "bronze_data"
        mainTableAlias: "data"
        joins:
        - - "Stats"
          - "s"
          - "Inner"
        joinExpressions:
        - - "True"
          - "data_Inner_s"
        columnMappings:
        - - "data.ID"
          - "ID"
        - - "data.VALUE"
          - "VALUE"
        - - "s.avg_VALUE"
          - "avg_VALUE"
        - - "s.stddev_pop_VALUE"
          - "stddev_pop_VALUE"
    Calculator:
      type: "calculator"
      sources:
      - "Join"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "ABS(\"avg_VALUE\" - \"VALUE\") > (2 * \"stddev_pop_VALUE\")"
          - "IsOutlier"
    Is Outlier:
      type: "filter"
      sources:
      - "Calculator"
      parameters:
        componentName: "Is Outlier"
        filterConditions:
        - - "IsOutlier"
          - "Is"
          - "Equal to"
          - "True"
        combineCondition: "And"
    Not Outlier:
      type: "filter"
      sources:
      - "Calculator"
      parameters:
        componentName: "Not Outlier"
        filterConditions:
        - - "IsOutlier"
          - "Not"
          - "Equal to"
          - "True"
        combineCondition: "And"
    Save for further processing:
      type: "rewrite-table"
      sources:
      - "Not Outlier"
      parameters:
        componentName: "Save for further processing"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "x"
        orderBy:
    Log outliers:
      type: "rewrite-table"
      sources:
      - "Is Outlier"
      parameters:
        componentName: "Log outliers"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "x"
        orderBy:
design:
  components:
    bronze_data:
      position:
        x: 40
        "y": 20
      tempMetlId: 1
    Stats:
      position:
        x: 170
        "y": 110
      tempMetlId: 2
    Join:
      position:
        x: 300
        "y": 20
      tempMetlId: 3
    Calculator:
      position:
        x: 430
        "y": 20
      tempMetlId: 4
    Is Outlier:
      position:
        x: 560
        "y": -60
      tempMetlId: 5
    Not Outlier:
      position:
        x: 560
        "y": 90
      tempMetlId: 6
    Save for further processing:
      position:
        x: 690
        "y": 90
      tempMetlId: 7
    Log outliers:
      position:
        x: 690
        "y": -60
      tempMetlId: 8
  notes:
    "1":
      position:
        x: 40
        "y": -120
      size:
        height: 98
        width: 400
      theme: "light-green"
      content: "Any records where the value is outside 2 standard deviations from\
        \ the mean will be logged as an outlier and not processed further"
