type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      parameters:
        componentName: "Start"
design:
  components:
    Start:
      position:
        x: -130
        "y": -20
      tempMetlId: 1
