type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create stg_task"
      parameters:
        componentName: "Start"
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mtln-ian"
        pattern: "Content/tasks-1205660689594801.csv"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "IAN"
        targetTable: "stg_task"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed: "\""
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "True"
    Create stg_task:
      type: "create-table"
      transitions:
        success:
        - "S3 Load"
      parameters:
        componentName: "Create stg_task"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "IAN"
        newTableName: "stg_task"
        tableType: "Permanent"
        columns:
        - - "gid"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "permalink_url"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "name"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "created_at"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "completed_at"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "completed"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "due_on"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "ContentType"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "DraftAccepted"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "TechnicalScore"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
design:
  components:
    Start:
      position:
        x: -90
        "y": 0
      tempMetlId: 1
    S3 Load:
      position:
        x: 140
        "y": 0
      tempMetlId: 2
    Create stg_task:
      position:
        x: 30
        "y": 0
      tempMetlId: 3
