type: "transformation"
version: "1.0"
pipeline:
  components:
    olympic_athletes:
      type: "table-input"
      parameters:
        componentName: "olympic_athletes"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "olympic_athletes"
        columnNames:
        - "ID"
        - "Name"
        - "Sex"
        - "Age"
        - "Height"
        - "Weight"
        - "Team"
        - "NOC"
        - "Games"
        - "Year"
        - "Season"
        - "City"
        - "Sport"
        - "Event"
        - "Medal"
        timeOffset:
    noc_region:
      type: "table-input"
      parameters:
        componentName: "noc_region"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "noc_region"
        columnNames:
        - "NOC"
        - "Region"
        - "Notes"
        timeOffset:
    Correct Naming:
      type: "calculator"
      sources:
      - "noc_region"
      parameters:
        componentName: "Correct Naming"
        includeInputColumns: "No"
        calculations:
        - - "\"NOC\""
          - "NOC"
        - - "COALESCE(\"Notes\", \"Region\")"
          - "Name"
    Athletes by country:
      type: "join"
      sources:
      - "Correct Naming"
      - "olympic_athletes"
      parameters:
        componentName: "Athletes by country"
        mainTable: "olympic_athletes"
        mainTableAlias: "ath"
        joins:
        - - "Correct Naming"
          - "noc"
          - "Left"
        joinExpressions:
        - - "\"ath\".\"NOC\" = \"noc\".\"NOC\""
          - "ath_Left_noc"
        columnMappings:
        - - "noc.NOC"
          - "NOC"
        - - "noc.Name"
          - "noc_Name"
        - - "ath.ID"
          - "ID"
        - - "ath.Name"
          - "ath_Name"
        - - "ath.Sex"
          - "Sex"
        - - "ath.Age"
          - "Age"
        - - "ath.Height"
          - "Height"
        - - "ath.Weight"
          - "Weight"
        - - "ath.Team"
          - "Team"
        - - "ath.Games"
          - "Games"
        - - "ath.Year"
          - "Year"
        - - "ath.Season"
          - "Season"
        - - "ath.City"
          - "City"
        - - "ath.Sport"
          - "Sport"
        - - "ath.Event"
          - "Event"
        - - "ath.Medal"
          - "Medal"
    Aggregate by Games and Event:
      type: "aggregate"
      sources:
      - "Athletes by country"
      parameters:
        componentName: "Aggregate by Games and Event"
        groupings:
        - "Year"
        - "Games"
        - "Event"
        aggregations:
        - - "noc_Name"
          - "Count Distinct"
        groupingType: "Group By"
    Rank by popularity:
      type: "rank"
      sources:
      - "Aggregate by Games and Event"
      parameters:
        componentName: "Rank by popularity"
        includeInputColumns: "Yes"
        partitionData:
        orderingWithinPartitions:
        - - "count_distinct_noc_Name"
          - "Descending"
        functions:
        - - "Row Number"
          - "list_position"
    Most Popular Event:
      type: "filter"
      sources:
      - "Rank by popularity"
      parameters:
        componentName: "Most Popular Event"
        filterConditions:
        - - "list_position"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
    Participants:
      type: "join"
      sources:
      - "Most Popular Event"
      - "Athletes by country"
      parameters:
        componentName: "Participants"
        mainTable: "Athletes by country"
        mainTableAlias: "ath"
        joins:
        - - "Most Popular Event"
          - "pop"
          - "Inner"
        joinExpressions:
        - - "\"ath\".\"Year\" = \"pop\".\"Year\"\r\nAND \"ath\".\"Games\" = \"pop\"\
            .\"Games\"\r\nAND \"ath\".\"Event\" = \"pop\".\"Event\""
          - "ath_Inner_pop"
        columnMappings:
        - - "pop.count_distinct_noc_Name"
          - "count_distinct_noc_Name"
        - - "pop.Year"
          - "pop_Year"
        - - "pop.Games"
          - "pop_Games"
        - - "pop.Event"
          - "pop_Event"
        - - "pop.list_position"
          - "list_position"
        - - "ath.NOC"
          - "NOC"
        - - "ath.noc_Name"
          - "noc_Name"
        - - "ath.ID"
          - "ID"
        - - "ath.ath_Name"
          - "ath_Name"
        - - "ath.Sex"
          - "Sex"
        - - "ath.Age"
          - "Age"
        - - "ath.Height"
          - "Height"
        - - "ath.Weight"
          - "Weight"
        - - "ath.Team"
          - "Team"
        - - "ath.Games"
          - "ath_Games"
        - - "ath.Year"
          - "ath_Year"
        - - "ath.Season"
          - "Season"
        - - "ath.City"
          - "City"
        - - "ath.Sport"
          - "Sport"
        - - "ath.Event"
          - "ath_Event"
        - - "ath.Medal"
          - "Medal"
    Pivot to List:
      type: "sql"
      sources:
      - "Participants"
      parameters:
        componentName: "Pivot to List"
        query: "SELECT LISTAGG(DISTINCT \"noc_Name\", ', ') AS \"Country_List\"\r\n\
          FROM $T{Participants}"
design:
  components:
    olympic_athletes:
      position:
        x: 200
        "y": -20
      tempMetlId: 1
    noc_region:
      position:
        x: 30
        "y": 230
      tempMetlId: 2
    Correct Naming:
      position:
        x: 140
        "y": 230
      tempMetlId: 3
    Athletes by country:
      position:
        x: 270
        "y": 120
      tempMetlId: 4
    Aggregate by Games and Event:
      position:
        x: 390
        "y": -10
      tempMetlId: 5
    Rank by popularity:
      position:
        x: 490
        "y": 60
      tempMetlId: 6
    Most Popular Event:
      position:
        x: 590
        "y": 130
      tempMetlId: 7
    Participants:
      position:
        x: 690
        "y": 220
      tempMetlId: 8
    Pivot to List:
      position:
        x: 810
        "y": 220
      tempMetlId: 9
  notes:
    "1":
      position:
        x: -70
        "y": -60
      size:
        height: 248
        width: 220
      theme: "white"
      content: |-
        Which Olympic event had participants from the most different countries?

        ![Image](https://upload.wikimedia.org/wikipedia/commons/a/ae/Olympic_flag.jpg)
