type: "transformation"
version: "1.0"
pipeline:
  components:
    mh_de_17fr8d5_OpenAI:
      type: "table-input"
      parameters:
        componentName: "mh_de_17fr8d5_OpenAI"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mh_de_17fr8d5_OpenAI"
        columnNames:
        - "section"
        - "DATA"
        timeOffset:
    Extract Nested Data:
      type: "extract-nested-data-sf"
      sources:
      - "mh_de_17fr8d5_OpenAI"
      parameters:
        componentName: "Extract Nested Data"
        includeInputColumns: "Yes"
        columns:
        - name: "motivation"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "motivation"
          isArray: "false"
          include: "true"
        - name: "self_esteem"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "self_esteem"
          isArray: "false"
          include: "true"
        - name: "prestige"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "prestige"
          isArray: "false"
          include: "true"
        - name: "esteem_score"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "esteem_score"
          isArray: "false"
          include: "true"
        - name: "actualization_score"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA"
          aliasName: "actualization_score"
          isArray: "false"
          include: "true"
        outerJoin: "No"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    Motivations:
      type: "aggregate"
      sources:
      - "Extract Nested Data"
      parameters:
        componentName: "Motivations"
        groupings:
        - "motivation"
        aggregations:
        - - "motivation"
          - "Count"
        groupingType: "Group By"
    Averages:
      type: "aggregate"
      sources:
      - "Extract Nested Data"
      parameters:
        componentName: "Averages"
        groupings:
        aggregations:
        - - "esteem_score"
          - "Average"
        - - "actualization_score"
          - "Average"
        groupingType: "Group By"
design:
  components:
    mh_de_17fr8d5_OpenAI:
      position:
        x: -190
        "y": 0
      tempMetlId: 1
    Extract Nested Data:
      position:
        x: 120
        "y": 0
      tempMetlId: 2
    Motivations:
      position:
        x: 380
        "y": 100
      tempMetlId: 3
    Averages:
      position:
        x: 380
        "y": -90
      tempMetlId: 4
  notes:
    "1":
      position:
        x: -250
        "y": -80
      size:
        height: 208
        width: 180
      theme: "white"
      content: "Data from the LLM analysis"
    "2":
      position:
        x: 20
        "y": -80
      size:
        height: 208
        width: 250
      theme: "light-green"
      content: "Sample this to view the outputs from the LLM analysis"
    "3":
      position:
        x: 330
        "y": -160
      size:
        height: 168
        width: 340
      theme: "white"
      content: "Sample this to view average **Esteem** and **Self Actualization**\
        \ scores"
    "4":
      position:
        x: 330
        "y": 30
      size:
        height: 168
        width: 340
      theme: "white"
      content: "Sample this to view the most common **Motivations** for data engineers"
