type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Sentiment Analysis - Acquire Review Data"
      parameters:
        componentName: "Start"
    Run Sentiment Analysis - Acquire Review Data:
      type: "run-transformation"
      transitions:
        unconditional:
        - "Run Sentiment Analysis - Call OpenAI GPT-4"
        - "Run Snowflake Cortex Hotel Review Comments"
      parameters:
        componentName: "Run Sentiment Analysis - Acquire Review Data"
        transformationJob: "Sentiment Analysis - Acquire Review Data"
        setScalarVariables:
        setGridVariables:
    Run Sentiment Analysis - Call OpenAI GPT-4:
      type: "run-orchestration"
      transitions:
        unconditional:
        - "And 2"
      parameters:
        componentName: "Run Sentiment Analysis - Call OpenAI GPT-4"
        orchestrationJob: "Sentiment Analysis - Call OpenAI GPT-4"
        setScalarVariables:
        setGridVariables:
    Run Snowflake Cortex Hotel Review Comments:
      type: "run-transformation"
      transitions:
        unconditional:
        - "And 2"
      parameters:
        componentName: "Run Snowflake Cortex Hotel Review Comments"
        transformationJob: "Snowflake Cortex Hotel Review Comments"
        setScalarVariables:
        setGridVariables:
    And 2:
      type: "and"
      parameters:
        componentName: "And 2"
design:
  components:
    Start:
      position:
        x: -260
        "y": -70
      tempMetlId: 1
    Run Sentiment Analysis - Acquire Review Data:
      position:
        x: -110
        "y": -60
      tempMetlId: 2
    Run Sentiment Analysis - Call OpenAI GPT-4:
      position:
        x: 50
        "y": -50
      tempMetlId: 3
    Run Snowflake Cortex Hotel Review Comments:
      position:
        x: 70
        "y": 90
      tempMetlId: 4
    And 2:
      position:
        x: 220
        "y": 20
      tempMetlId: 6
