type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Salesforce OpportunityContactRole"
        - "Salesforce Contact"
        - "Salesforce Opportunity"
        - "Salesforce Account"
      parameters:
        componentName: "Start"
    Salesforce OpportunityContactRole:
      type: "salesforce-query"
      parameters:
        componentName: "Salesforce OpportunityContactRole"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "OpportunityContactRole"
        dataSelection:
        - "Id"
        - "ContactId"
        - "OpportunityId"
        - "Role"
        - "IsPrimary"
        - "CreatedDate"
        - "LastModifiedDate"
        dataSourceFilter:
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_campaignmember"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Salesforce Contact:
      type: "salesforce-query"
      parameters:
        componentName: "Salesforce Contact"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "Contact"
        dataSelection:
        - "Id"
        - "Name"
        dataSourceFilter:
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contact"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Salesforce Opportunity:
      type: "salesforce-query"
      parameters:
        componentName: "Salesforce Opportunity"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "Opportunity"
        dataSelection:
        - "Id"
        - "AccountId"
        - "CloseDate"
        - "StageName"
        - "CreatedDate"
        - "LastModifiedDate"
        - "OwnerId"
        - "Name"
        - "Description"
        - "Type"
        dataSourceFilter:
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_lead"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Salesforce Account:
      type: "salesforce-query"
      parameters:
        componentName: "Salesforce Account"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "Account"
        dataSelection:
        - "Id"
        - "Name"
        - "BillingCountry"
        - "BillingState"
        - "OwnerId"
        dataSourceFilter:
        combineFilters: "And"
        limit: ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
  variables:
    SalesforceOAuthName:
      metadata:
        type: "TEXT"
        description: "Name of your Salesforce OAuth"
        scope: "COPIED"
        visibility: "PRIVATE"
      defaultValue: "Your-Salesforce-OAuth-name"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Salesforce OpportunityContactRole:
      position:
        x: 150
        "y": -200
      tempMetlId: 4
    Salesforce Contact:
      position:
        x: 190
        "y": -30
      tempMetlId: 6
    Salesforce Opportunity:
      position:
        x: 260
        "y": 90
      tempMetlId: 7
    Salesforce Account:
      position:
        x: 150
        "y": 200
      tempMetlId: 8
