type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Truncate Table"
      parameters:
        componentName: "Start"
    Amazon Bedrock Prompt:
      type: "ai-prompt"
      parameters:
        componentName: "Amazon Bedrock Prompt"
        service:
          provider: "Amazon Bedrock"
          aws:
            region: "eu-central-1"
            modelCategory: "Anthropic"
            anthropic:
              model: "anthropic.claude-v2.1"
              temperature: "0.5"
              maxTokens: "200"
        source:
          snowflake:
            database: "[Environment Default]"
            schema: "[Environment Default]"
            table: "BARISTA_REVIEWS"
            keyColumn: "name"
            limit: ""
        promptContext:
          userContext: "You're a marketing analyst reviewing user comments from a\
            \ well-known barista company."
          inputs:
          - - "name"
            - "name"
          - - "review"
            - "review"
          outputFormat: "JSON"
          outputs:
          - - "anger_score"
            - "Give a score between 0 and 10 on the level of anger you feel in the\
              \ user's review"
          - - "anger_reason"
            - "Give a single word describing the reason why the user is angry. In\
              \ the case of a positive review, keep the field blank. Remember, not\
              \ two words, just ONE!"
          - - "sentiment"
            - "Answer by \"Positive\", \"Neutral\", \"Negative\" based on the sentiment\
              \ of the user's comment."
          - - "anger_summary"
            - "Give a humorous summary of the user comment, in a single sentence that\
              \ could have been written by a barista. Remember to keep it really fun!"
          - - "swear_words"
            - "Answer \"Yes\" if you found swear words in the user review. Otherwise,\
              \ answer by \"No\""
          - - "product_involved"
            - "Extract the product name involved in the user comment. Keep the field\
              \ blank if you can't find any."
          - - "wont_return"
            - "Answer \"Yes\" if the user indicates that they will never come again\
              \ to the shop. Otherwise, answer \"No\". "
        destination:
          snowflake:
            database: "[Environment Default]"
            schema: "[Environment Default]"
            table: "BARISTA_REVIEWS_PROCESSED_BEDROCK_CLAUDE21"
            createTableOptions: "Replace if Table Exists"
    Truncate Table:
      type: "truncate-table"
      transitions:
        unconditional:
        - "Amazon Bedrock Prompt"
      parameters:
        componentName: "Truncate Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable:
        - "BARISTA_REVIEWS_PROCESSED"
design:
  components:
    Start:
      position:
        x: -960
        "y": -90
      tempMetlId: 1
    Amazon Bedrock Prompt:
      position:
        x: -610
        "y": -90
      tempMetlId: 2
    Truncate Table:
      position:
        x: -790
        "y": -90
      tempMetlId: 3
