type: "transformation"
version: "1.0"
pipeline:
  components:
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_contact"
      - "mtln_qs_sf_user"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_account"
        mainTableAlias: "ccna1"
        joins:
        - - "mtln_qs_sf_user"
          - "sra2"
          - "Left"
        - - "mtln_qs_sf_contact"
          - "cnta3"
          - "Left"
        joinExpressions:
        - - "\"ccna1\".\"OwnerId\" = \"sra2\".\"Id\""
          - "ccna1_Left_sra2"
        - - "\"ccna1\".\"Primary_Contact__c\" = \"cnta3\".\"Id\""
          - "ccna1_Left_cnta3"
        columnMappings:
        - - "ccna1.Id"
          - "ccna1_Id"
        - - "ccna1.Name"
          - "ccna1_Name"
        - - "ccna1.OwnerId"
          - "ccna1_OwnerId"
        - - "ccna1.Company_Data__c"
          - "ccna1_Company_Data__c"
        - - "ccna1.BillingCountry"
          - "ccna1_BillingCountry"
        - - "ccna1.BillingState"
          - "ccna1_BillingState"
        - - "ccna1.Partner__c"
          - "ccna1_Partner__c"
        - - "ccna1.Primary_Contact__c"
          - "ccna1_Primary_Contact__c"
        - - "ccna1.Secondary_Contact__c"
          - "ccna1_Secondary_Contact__c"
        - - "sra2.Id"
          - "sra2_Id"
        - - "sra2.Name"
          - "sra2_Name"
        - - "cnta3.Id"
          - "cnta3_Id"
        - - "cnta3.Name"
          - "cnta3_Name"
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
        - "OwnerId"
        - "Company_Data__c"
        - "BillingCountry"
        - "BillingState"
        - "Partner__c"
        - "Primary_Contact__c"
        - "Secondary_Contact__c"
    mtln_qs_sf_user:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_user"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_user"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
    mtln_qs_sf_contact:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_contact"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contact"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
design:
  components:
    Join:
      position:
        x: 0
        y: -150
      tempMetlId: 1
    mtln_qs_sf_account:
      position:
        x: 0
        y: -50
      tempMetlId: 2
    mtln_qs_sf_user:
      position:
        x: 0
        y: 50
      tempMetlId: 3
    mtln_qs_sf_contact:
      position:
        x: 0
        y: 150
      tempMetlId: 4
