type: "transformation"
version: "1.0"
pipeline:
  components:
    mtln_qs_sf_task:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_task"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_task"
        columnNames:
        - "Id"
        - "AccountId"
        - "ActivityDate"
        - "CreatedById"
        - "CreatedDate"
        - "CurrencyIsoCode"
        - "Description"
        - "IsArchived"
        - "IsDeleted"
        - "IsRecurrence"
        - "IsReminderSet"
        - "LastModifiedById"
        - "LastModifiedDate"
        - "OwnerId"
        - "RecordTypeId"
        - "RecurrenceActivityId"
        - "RecurrenceDayOfMonth"
        - "RecurrenceDayOfWeekMask"
        - "RecurrenceEndDateOnly"
        - "RecurrenceInstance"
        - "RecurrenceInterval"
        - "RecurrenceMonthOfYear"
        - "RecurrenceTimeZoneSidKey"
        - "RecurrenceType"
        - "ReminderDateTime"
        - "Subject"
        - "SystemModstamp"
        - "Type"
        - "WhatCount"
        - "WhatId"
        - "WhoCount"
        - "WhoId"
        timeOffset:
    mtln_qs_sf_event:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_event"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_event"
        columnNames:
        - "Id"
        - "AccountId"
        - "ActivityDate"
        - "CreatedById"
        - "CreatedDate"
        - "CurrencyIsoCode"
        - "Description"
        - "IsArchived"
        - "IsDeleted"
        - "IsRecurrence"
        - "IsReminderSet"
        - "LastModifiedById"
        - "LastModifiedDate"
        - "OwnerId"
        - "RecordTypeId"
        - "RecurrenceActivityId"
        - "RecurrenceDayOfMonth"
        - "RecurrenceDayOfWeekMask"
        - "RecurrenceEndDateOnly"
        - "RecurrenceInstance"
        - "RecurrenceInterval"
        - "RecurrenceMonthOfYear"
        - "RecurrenceTimeZoneSidKey"
        - "RecurrenceType"
        - "ReminderDateTime"
        - "Subject"
        - "SystemModstamp"
        - "Type"
        - "WhatCount"
        - "WhatId"
        - "WhoCount"
        - "WhoId"
        timeOffset:
    Calculator:
      type: "calculator"
      sources:
      - "mtln_qs_sf_task"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "'Task'"
          - "ActivityType"
    Calculator 2:
      type: "calculator"
      sources:
      - "mtln_qs_sf_event"
      parameters:
        componentName: "Calculator 2"
        includeInputColumns: "Yes"
        calculations:
        - - "'Event'"
          - "ActivityType"
    Rename:
      type: "rename"
      sources:
      - "Calculator"
      parameters:
        componentName: "Rename"
        columnMapping:
        - - "Id"
          - "ActivityId"
        - - "AccountId"
          - "AccountId"
        - - "ActivityDate"
          - "ActivityDate"
        - - "CreatedById"
          - "CreatedById"
        - - "CreatedDate"
          - "CreatedDate"
        - - "CurrencyIsoCode"
          - "CurrencyIsoCode"
        - - "Description"
          - "Description"
        - - "IsArchived"
          - "IsArchived"
        - - "IsDeleted"
          - "IsDeleted"
        - - "IsRecurrence"
          - "IsRecurrence"
        - - "IsReminderSet"
          - "IsReminderSet"
        - - "LastModifiedById"
          - "LastModifiedById"
        - - "LastModifiedDate"
          - "LastModifiedDate"
        - - "OwnerId"
          - "OwnerId"
        - - "RecordTypeId"
          - "RecordTypeId"
        - - "RecurrenceActivityId"
          - "RecurrenceActivityId"
        - - "RecurrenceDayOfMonth"
          - "RecurrenceDayOfMonth"
        - - "RecurrenceDayOfWeekMask"
          - "RecurrenceDayOfWeekMask"
        - - "RecurrenceEndDateOnly"
          - "RecurrenceEndDateOnly"
        - - "RecurrenceInstance"
          - "RecurrenceInstance"
        - - "RecurrenceInterval"
          - "RecurrenceInterval"
        - - "RecurrenceMonthOfYear"
          - "RecurrenceMonthOfYear"
        - - "RecurrenceTimeZoneSidKey"
          - "RecurrenceTimeZoneSidKey"
        - - "RecurrenceType"
          - "RecurrenceType"
        - - "ReminderDateTime"
          - "ReminderDateTime"
        - - "Subject"
          - "Subject"
        - - "SystemModstamp"
          - "SystemModstamp"
        - - "Type"
          - "Type"
        - - "WhatCount"
          - "WhatCount"
        - - "WhatId"
          - "WhatId"
        - - "WhoCount"
          - "WhoCount"
        - - "WhoId"
          - "WhoId"
        - - "ActivityType"
          - "ActivityType"
        includeInputColumns: "No"
    Rename 2:
      type: "rename"
      sources:
      - "Calculator 2"
      parameters:
        componentName: "Rename 2"
        columnMapping:
        - - "Id"
          - "ActivityId"
        - - "AccountId"
          - "AccountId"
        - - "ActivityDate"
          - "ActivityDate"
        - - "CreatedById"
          - "CreatedById"
        - - "CreatedDate"
          - "CreatedDate"
        - - "CurrencyIsoCode"
          - "CurrencyIsoCode"
        - - "Description"
          - "Description"
        - - "IsArchived"
          - "IsArchived"
        - - "IsDeleted"
          - "IsDeleted"
        - - "IsRecurrence"
          - "IsRecurrence"
        - - "IsReminderSet"
          - "IsReminderSet"
        - - "LastModifiedById"
          - "LastModifiedById"
        - - "LastModifiedDate"
          - "LastModifiedDate"
        - - "OwnerId"
          - "OwnerId"
        - - "RecordTypeId"
          - "RecordTypeId"
        - - "RecurrenceActivityId"
          - "RecurrenceActivityId"
        - - "RecurrenceDayOfMonth"
          - "RecurrenceDayOfMonth"
        - - "RecurrenceDayOfWeekMask"
          - "RecurrenceDayOfWeekMask"
        - - "RecurrenceEndDateOnly"
          - "RecurrenceEndDateOnly"
        - - "RecurrenceInstance"
          - "RecurrenceInstance"
        - - "RecurrenceInterval"
          - "RecurrenceInterval"
        - - "RecurrenceMonthOfYear"
          - "RecurrenceMonthOfYear"
        - - "RecurrenceTimeZoneSidKey"
          - "RecurrenceTimeZoneSidKey"
        - - "RecurrenceType"
          - "RecurrenceType"
        - - "ReminderDateTime"
          - "ReminderDateTime"
        - - "Subject"
          - "Subject"
        - - "SystemModstamp"
          - "SystemModstamp"
        - - "Type"
          - "Type"
        - - "WhatCount"
          - "WhatCount"
        - - "WhatId"
          - "WhatId"
        - - "WhoCount"
          - "WhoCount"
        - - "WhoId"
          - "WhoId"
        - - "ActivityType"
          - "ActivityType"
        includeInputColumns: "No"
    Unite:
      type: "unite"
      sources:
      - "Rename"
      - "Rename 2"
      parameters:
        componentName: "Unite"
        method: "All Columns"
        castTypes: "Yes"
        addSourceComponentColumn: "No"
        removeDuplicates: "No"
    Rewrite mtln_qs_sf_activity:
      type: "rewrite-table"
      sources:
      - "Unite"
      parameters:
        componentName: "Rewrite mtln_qs_sf_activity"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_activity"
        orderBy:
    mtln_qs_sf_record_type (task):
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_record_type (task)"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_record_type"
        columnNames:
        - "Id"
        - "Name"
        timeOffset:
    mtln_qs_sf_record_type (event):
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_record_type (event)"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_record_type"
        columnNames:
        - "Id"
        - "Name"
        timeOffset:
design:
  components:
    mtln_qs_sf_task:
      position:
        x: 0
        "y": -50
      tempMetlId: 4
    mtln_qs_sf_event:
      position:
        x: 0
        "y": 50
      tempMetlId: 5
    Calculator:
      position:
        x: 120
        "y": -50
      tempMetlId: 6
    Calculator 2:
      position:
        x: 120
        "y": 50
      tempMetlId: 7
    Rename:
      position:
        x: 240
        "y": -50
      tempMetlId: 8
    Rename 2:
      position:
        x: 240
        "y": 50
      tempMetlId: 9
    Unite:
      position:
        x: 360
        "y": 0
      tempMetlId: 10
    Rewrite mtln_qs_sf_activity:
      position:
        x: 480
        "y": 0
      tempMetlId: 11
    mtln_qs_sf_record_type (task):
      position:
        x: 0
        "y": -150
      tempMetlId: 12
    mtln_qs_sf_record_type (event):
      position:
        x: 0
        "y": 150
      tempMetlId: 13
  notes:
    "1":
      position:
        x: -310
        "y": -40
      size:
        height: 108
        width: 250
      theme: "white"
      content: "`Id`s become `ActivityId`s in the target table"
