type: "transformation"
version: "1.0"
pipeline:
  components:
    mtln_qs_sf_campaignmember:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_campaignmember"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_campaignmember"
        timeOffset:
        columnNames:
        - "Id"
        - "ContactId"
        - "LeadId"
        - "Status"
        - "CreatedDate"
        - "ClosedDate"
    mtln_qs_sf_contact:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_contact"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contact"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
        - "AccountId"
    mtln_qs_sf_lead:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_lead"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_lead"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
        - "ConvertedContactId"
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
        - "BillingCountry"
        - "BillingState"
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_campaignmember"
      - "mtln_qs_sf_contact"
      - "mtln_qs_sf_lead"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_campaignmember"
        mainTableAlias: "cmpa1"
        joins:
        - - "mtln_qs_sf_contact"
          - "cnta2"
          - "Inner"
        - - "mtln_qs_sf_lead"
          - "lda3"
          - "Left"
        - - "mtln_qs_sf_account"
          - "ccna4"
          - "Left"
        joinExpressions:
        - - "\"cmpa1\".\"ContactId\" = \"cnta2\".\"Id\""
          - "cmpa1_Inner_cnta2"
        - - "\"cmpa1\".\"LeadId\" = \"lda3\".\"Id\""
          - "cmpa1_Left_lda3"
        - - "\"cnta2\".\"AccountId\" = \"ccna4\".\"Id\""
          - "cmpa1_Left_ccna4"
        columnMappings:
        - - "cmpa1.Id"
          - "cmpa1_Id"
        - - "cmpa1.ContactId"
          - "cmpa1_ContactId"
        - - "cmpa1.LeadId"
          - "cmpa1_LeadId"
        - - "cmpa1.Status"
          - "cmpa1_Status"
        - - "cmpa1.CreatedDate"
          - "cmpa1_CreatedDate"
        - - "cmpa1.ClosedDate"
          - "cmpa1_ClosedDate"
        - - "cnta2.Id"
          - "cnta2_Id"
        - - "cnta2.Name"
          - "cnta2_Name"
        - - "cnta2.AccountId"
          - "cnta2_AccountId"
        - - "lda3.Id"
          - "lda3_Id"
        - - "lda3.Name"
          - "lda3_Name"
        - - "lda3.ConvertedContactId"
          - "lda3_ConvertedContactId"
        - - "ccna4.Id"
          - "ccna4_Id"
        - - "ccna4.Name"
          - "ccna4_Name"
        - - "ccna4.BillingCountry"
          - "ccna4_BillingCountry"
        - - "ccna4.BillingState"
          - "ccna4_BillingState"
    Filter:
      type: "filter"
      sources:
      - "Join"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "cmpa1_Id"
          - "Not"
          - "Null or blank"
          - ""
        combineCondition: "And"
    Rewrite mtln_qs_sf_campaigns_with_contacts_or_leads:
      type: "rewrite-table"
      sources:
      - "Filter"
      parameters:
        componentName: "Rewrite mtln_qs_sf_campaigns_with_contacts_or_leads"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_campaigns_with_contacts_or_leads"
        warehouse: "[Environment Default]"
        orderBy:
design:
  components:
    mtln_qs_sf_campaignmember:
      position:
        x: 0
        y: -150
      tempMetlId: 4
    mtln_qs_sf_contact:
      position:
        x: 0
        y: -50
      tempMetlId: 5
    mtln_qs_sf_lead:
      position:
        x: 0
        y: 50
      tempMetlId: 6
    mtln_qs_sf_account:
      position:
        x: 0
        y: 150
      tempMetlId: 7
    Join:
      position:
        x: 150
        y: 0
      tempMetlId: 1
    Filter:
      position:
        x: 300
        y: 0
      tempMetlId: 2
    Rewrite mtln_qs_sf_campaigns_with_contacts_or_leads:
      position:
        x: 450
        y: 0
      tempMetlId: 3
  notes:
    1:
      position:
        x: 200
        y: -130
      size:
        height: 200
        width: 240
      theme: "white"
      content: "Add your own filters here if you want to apply them before the integra\
        ted report is generated"
    2:
      position:
        x: -370
        y: -100
      size:
        height: 100
        width: 300
      theme: "white"
      content: "Add your own Table Inputs here to customize the integration with your \
        own data"
