type: "transformation"
version: "1.0"
pipeline:
  components:
    mtln_qs_sf_account:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_account"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
        - "OwnerId"
        - "BillingCountry"
        - "BillingState"
    mtln_qs_sf_user:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_user"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_user"
        timeOffset:
        columnNames:
        - "Id"
        - "Name"
    mtln_qs_sf_contact:
      type: "table-input"
      parameters:
        componentName: "mtln_qs_sf_contact"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contact"
        timeOffset:
        columnNames:
        - "Id"
        - "AccountId"
        - "Name"
    Join:
      type: "join"
      sources:
      - "mtln_qs_sf_account"
      - "mtln_qs_sf_contact"
      - "mtln_qs_sf_user"
      parameters:
        componentName: "Join"
        mainTable: "mtln_qs_sf_account"
        mainTableAlias: "ccna3"
        joins:
        - - "mtln_qs_sf_user"
          - "sra4"
          - "Left"
        - - "mtln_qs_sf_contact"
          - "cnta5"
          - "Left"
        joinExpressions:
        - - "\"ccna3\".\"OwnerId\" = \"sra4\".\"Id\""
          - "ccna3_Left_sra4"
        - - "\"ccna3\".\"Id\" = \"cnta5\".\"AccountId\""
          - "ccna3_Left_cnta5"
        columnMappings:
        - - "ccna3.Id"
          - "ccna3_Id"
        - - "ccna3.Name"
          - "ccna3_Name"
        - - "ccna3.OwnerId"
          - "ccna3_OwnerId"
        - - "ccna3.BillingCountry"
          - "ccna3_BillingCountry"
        - - "ccna3.BillingState"
          - "ccna3_BillingState"
        - - "sra4.Id"
          - "sra4_Id"
        - - "sra4.Name"
          - "sra4_Name"
        - - "cnta5.Id"
          - "cnta5_Id"
        - - "cnta5.AccountId"
          - "cnta5_AccountId"
        - - "cnta5.Name"
          - "cnta5_Name"
    Filter:
      type: "filter"
      sources:
      - "Join"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "sra1_Id"
          - "Not"
          - "Null or blank"
          - ""
        combineCondition: "And"
design:
  components:
    mtln_qs_sf_account:
      position:
        x: 0
        y: -100
      tempMetlId: 3
    mtln_qs_sf_user:
      position:
        x: 0
        y: 0
      tempMetlId: 4
    mtln_qs_sf_contact:
      position:
        x: 0
        y: 100
      tempMetlId: 5
    Join:
      position:
        x: 150
        y: 0
      tempMetlId: 1
    Filter:
      position:
        x: 300
        y: 0
      tempMetlId: 2
