type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "h_prospect"
      parameters:
        componentName: "Start"
    h_prospect:
      type: "create-table"
      transitions:
        success:
        - "Run Sales Sentiment - Load Hub"
      parameters:
        componentName: "h_prospect"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "h_prospect"
        tableType: "Permanent"
        columns:
        - - "sk"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "Yes"
          - ""
        - - "prospect_id"
          - "NUMBER"
          - "8"
          - "0"
          - ""
          - "Yes"
          - "Yes"
          - ""
        - - "load_timestamp"
          - "TIMESTAMP_NTZ"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "record_source"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    s_prospect_gong:
      type: "create-table"
      transitions:
        success:
        - "Run Sales Sentiment - Load Gong"
      parameters:
        componentName: "s_prospect_gong"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "s_prospect_gong"
        tableType: "Permanent"
        columns:
        - - "sk"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "Yes"
          - ""
        - - "prospect_sk"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "id"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "text"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "load_timestamp"
          - "TIMESTAMP_NTZ"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "record_source"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    s_prospect_salesloft:
      type: "create-table"
      transitions:
        success:
        - "Run Sales Sentiment - Load Salesloft"
      parameters:
        componentName: "s_prospect_salesloft"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "s_prospect_salesloft"
        tableType: "Permanent"
        columns:
        - - "sk"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "Yes"
          - ""
        - - "prospect_sk"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "id"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "text"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "load_timestamp"
          - "TIMESTAMP_NTZ"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "record_source"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    s_prospect_opportunity:
      type: "create-table"
      transitions:
        success:
        - "Run Sales Sentiment - Load Opportunity"
      parameters:
        componentName: "s_prospect_opportunity"
        createReplace: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        newTableName: "s_prospect_opportunity"
        tableType: "Permanent"
        columns:
        - - "sk"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "Yes"
          - ""
        - - "prospect_sk"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "id"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "text"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "load_timestamp"
          - "TIMESTAMP_NTZ"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        - - "record_source"
          - "VARCHAR"
          - ""
          - ""
          - ""
          - "Yes"
          - "No"
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
    Run Sales Sentiment - Load Hub:
      type: "run-transformation"
      transitions:
        success:
        - "s_prospect_gong"
        - "s_prospect_salesloft"
        - "s_prospect_opportunity"
      parameters:
        componentName: "Run Sales Sentiment - Load Hub"
        transformationJob: "Sales Sentiment - Load Hub"
        setScalarVariables:
        setGridVariables:
    Run Sales Sentiment - Load Gong:
      type: "run-transformation"
      parameters:
        componentName: "Run Sales Sentiment - Load Gong"
        transformationJob: "Sales Sentiment - Load Gong"
        setScalarVariables:
        setGridVariables:
    Run Sales Sentiment - Load Salesloft:
      type: "run-transformation"
      parameters:
        componentName: "Run Sales Sentiment - Load Salesloft"
        transformationJob: "Sales Sentiment - Load Salesloft"
        setScalarVariables:
        setGridVariables:
    Run Sales Sentiment - Load Opportunity:
      type: "run-transformation"
      parameters:
        componentName: "Run Sales Sentiment - Load Opportunity"
        transformationJob: "Sales Sentiment - Load Opportunity"
        setScalarVariables:
        setGridVariables:
design:
  components:
    Start:
      position:
        x: -190
        "y": 0
      tempMetlId: 1
    h_prospect:
      position:
        x: -30
        "y": 0
      tempMetlId: 2
    s_prospect_gong:
      position:
        x: 320
        "y": -110
      tempMetlId: 3
    s_prospect_salesloft:
      position:
        x: 320
        "y": 0
      tempMetlId: 4
    s_prospect_opportunity:
      position:
        x: 320
        "y": 110
      tempMetlId: 5
    Run Sales Sentiment - Load Hub:
      position:
        x: 130
        "y": 0
      tempMetlId: 6
    Run Sales Sentiment - Load Gong:
      position:
        x: 510
        "y": -110
      tempMetlId: 7
    Run Sales Sentiment - Load Salesloft:
      position:
        x: 510
        "y": 0
      tempMetlId: 8
    Run Sales Sentiment - Load Opportunity:
      position:
        x: 510
        "y": 110
      tempMetlId: 9
