type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Salesforce Account"
        - "Salesforce UserRole"
      parameters:
        componentName: "Start"
    Salesforce Account:
      type: "salesforce-query"
      transitions:
        success:
        - "Sync"
      parameters:
        componentName: "Salesforce Account"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "Account"
        dataSelection:
        - "Id"
        - "Name"
        - "Company_Data__c"
        dataSourceFilter:
        combineFilters: "And"
        limit: "100"
        database: "[Environment Default]"
        primaryKeys:
        schema: "[Environment Default]"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        targetTable: "mtln_qs_sf_account"
        type: "Standard"
        warehouse: "[Environment Default]"
        loadOptions:
        autoDebug: "Off"
    Salesforce UserRole:
      type: "salesforce-query"
      transitions:
        success:
        - "Sync"
      parameters:
        componentName: "Salesforce UserRole"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "UserRole"
        dataSelection:
        - "Id"
        - "Name"
        dataSourceFilter:
        combineFilters: "And"
        limit: "100"
        database: "[Environment Default]"
        primaryKeys:
        schema: "[Environment Default]"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        targetTable: "mtln_qs_sf_userrole"
        type: "Standard"
        warehouse: "[Environment Default]"
        loadOptions:
        autoDebug: "Off"
    Sync:
      type: "and"
      transitions:
        success:
        - "RunTran"
      parameters:
        componentName: "Sync"
    RunTran:
      type: "run-transformation"
      parameters:
        componentName: "RunTran"
        transformationJob: "Thingy"
        setScalarVariables:
        setGridVariables:
  variables:
    SalesforceOAuthName:
      metadata:
        type: "TEXT"
        description: "Name of your Salesforce OAuth"
        scope: "COPIED"
        visibility: "PRIVATE"
      defaultValue: "Salesforce-2024"
design:
  components:
    Start:
      position:
        x: 0
        y: 0
      tempMetlId: 1
    Salesforce Account:
      position:
        x: 150
        y: -50
      tempMetlId: 2
    Salesforce UserRole:
      position:
        x: 150
        y: 50
      tempMetlId: 3
    Sync:
      position:
        x: 300
        y: 0
      tempMetlId: 4
    RunTran:
      position:
        x: 450
        y: 0
      tempMetlId: 5
