type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Salesforce Query"
      parameters:
        componentName: "Start"
    Salesforce Query:
      type: "salesforce-query"
      parameters:
        componentName: "Salesforce Query"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "Salesforce-2024"
        connectionOptions:
        dataSource: "Contact"
        dataSelection:
        - "Id"
        - "Name"
        - "AccountId"
        dataSourceFilter:
        combineFilters: "And"
        limit: "100"
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_contact"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
design:
  components:
    Start:
      position:
        x: -60
        "y": -10
      tempMetlId: 1
    Salesforce Query:
      position:
        x: 130
        "y": -10
      tempMetlId: 2
