type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Salesforce Account"
        - "Salesforce Company_Data__c"
      parameters:
        componentName: "Start"
    Salesforce Account:
      type: "salesforce-query"
      transitions:
        success:
        - "And"
      parameters:
        componentName: "Salesforce Account"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "UserRole"
        dataSelection:
        - "Id"
        - "Name"
        dataSourceFilter:
        combineFilters: "And"
        limit: "100"
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_account"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    Salesforce Company_Data__c:
      type: "salesforce-query"
      transitions:
        success:
        - "And"
      parameters:
        componentName: "Salesforce Company_Data__c"
        basicAdvancedMode: "Basic"
        authenticationMethod: "OAuth"
        useSandbox: "No"
        authentication: "${SalesforceOAuthName}"
        connectionOptions:
        dataSource: "Company_Data__c"
        dataSelection:
        - "Id"
        - "Name"
        dataSourceFilter:
        combineFilters: "And"
        limit: "100"
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "mtln_qs_sf_company_data__c"
        stage: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        autoDebug: "Off"
    And:
      type: "and"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "And"
    Run Transformation:
      type: "run-transformation"
      parameters:
        componentName: "Run Transformation"
        transformationJob:
        setScalarVariables:
        setGridVariables:
  variables:
    SalesforceOAuthName:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PRIVATE"
      defaultValue: "Salesforce-2024"
design:
  components:
    Start:
      position:
        x: -10
        "y": -10
      tempMetlId: 1
    Salesforce Account:
      position:
        x: 130
        "y": -70
      tempMetlId: 2
    Salesforce Company_Data__c:
      position:
        x: 130
        "y": 50
      tempMetlId: 3
    And:
      position:
        x: 280
        "y": 20
      tempMetlId: 4
    Run Transformation:
      position:
        x: 420
        "y": -10
      tempMetlId: 5
  notes:
    "1":
      position:
        x: -310
        "y": -130
      size:
        height: 88
        width: 340
      theme: "light-red"
      content: "Remember to set the default value of the `SalesforceOAuthName` pipeline\
        \ variable"
