type: "transformation"
version: "1.0"
pipeline:
  components:
    stg_batteryelectric_wide:
      type: "table-input"
      parameters:
        componentName: "stg_batteryelectric_wide"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "stg_batteryelectric_wide"
        columnNames:
        - "Make"
        - "Model"
        - "2022 Q3"
        - "2022 Q2"
        - "2022 Q1"
        - "2021 Q4"
        - "2021 Q3"
        - "2021 Q2"
        - "2021 Q1"
        - "2020 Q4"
        - "2020 Q3"
        - "2020 Q2"
        - "2020 Q1"
        - "2019 Q4"
        - "2019 Q3"
        - "2019 Q2"
        - "2019 Q1"
        - "2018 Q4"
        - "2018 Q3"
        - "2018 Q2"
        - "2018 Q1"
        - "2017 Q4"
        - "2017 Q3"
        - "2017 Q2"
        - "2017 Q1"
        - "2016 Q4"
        - "2016 Q3"
        - "2016 Q2"
        - "2016 Q1"
        - "2015 Q4"
        - "2015 Q3"
        - "2015 Q2"
        - "2015 Q1"
        - "2014 Q4"
        - "2014 Q3"
        - "2014 Q2"
        - "2014 Q1"
        - "2013 Q4"
        - "2013 Q3"
        - "2013 Q2"
        - "2013 Q1"
        - "2012 Q4"
        - "2012 Q3"
        - "2012 Q2"
        - "2012 Q1"
        - "2011 Q4"
        - "2011 Q3"
        - "2011 Q2"
        - "2011 Q1"
        - "2010 Q4"
        - "2010 Q3"
        - "2010 Q2"
        - "2010 Q1"
        timeOffset:
    UNPIVOT - wide to narrow:
      type: "sql"
      sources:
      - "stg_batteryelectric_wide"
      parameters:
        componentName: "UNPIVOT - wide to narrow"
        query: "SELECT * FROM $T{stg_batteryelectric_wide}"
  variables:
    jv_col_list:
      metadata:
        type: "TEXT"
        description: "List of columns to unpivot"
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    stg_batteryelectric_wide:
      position:
        x: 520
        "y": 170
      tempMetlId: 1
    UNPIVOT - wide to narrow:
      position:
        x: 760
        "y": 170
      tempMetlId: 2
